language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install . --use-mirrors"
  - "pip install pytest-cov pytest-pep8 coveralls --use-mirrors"
script: py.test
after_success:
  coveralls
